swagger: '2.0'
info:
  title: v1
  version: '1.0'
host: stagingapi.webops.net/api
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
paths:
  /procedures:
    post:
      operationId: get_procedures
      summary: Get Procedures
      
      parameters:
        - name: body
          in: body
          schema:
            allOf:
              - $ref: ../../common/message-data.yaml
              - $ref: ../../docs/procedures/procedure-identifiers-1.yaml
              - $ref: ../../common/updated.yaml
              - $ref: ../../common/paging.yaml
              - type: object
                properties:
                  includeDetails:
                    type: boolean
                    example: true
                    description: 'Include procedure categories in response - Default = false (Yes = true, No = false)'
            description: Procedures
        - $ref: ../../common/headers/authorization.yaml
        - $ref: ../../common/headers/access-token.yaml
      responses:
        '200':
          description: ''
          schema:
            type: object
            required:
              - messageId
              - timestamp
            properties:
              messageId:
                type: string
                example: 2d648c64-3eee-4fc7-9e19-df6f14c3fefd
                description: Message ID of the request
              timestamp:
                type: string
                format: date-time
                example: '2018-11-05T13:15:30Z'
                description: Current date/time in ISO-8601 Z format
              procedures:
                type: array
                items:
                  $ref: ../../docs/procedures/procedure-1.yaml
        '403':
          description: ''
          schema:
            $ref: ../../common/responses/error-403.yaml
        '422':
          description: ''
          schema:
            $ref: ../../common/responses/error-422.yaml
        '500':
          description: ''
          schema:
            $ref: ../../common/responses/error-500.yaml
  /procedures/count:
    post:
      operationId: procedures_count
      summary: Get total number of procedures per defined parameters. Must be used in conjunction with /procedures
      
      parameters:
        - name: body
          in: body
          schema:
            allOf:
              - $ref: ../../common/message-data.yaml
              - $ref: ../../docs/procedures/procedure-identifiers-1.yaml
              - $ref: ../../common/updated.yaml
              - type: object
                properties:
                  includeDetails:
                    type: boolean
                    example: true
                    description: 'Get the count for using includeDetails on procedures list - Default = false (Yes = true, No = false)'
            description: Sales Reps
        - $ref: ../../common/headers/authorization.yaml
        - $ref: ../../common/headers/access-token.yaml
      responses:
        '200':
          description: ''
          schema:
            $ref: ../../common/responses/count.yaml
        '403':
          description: ''
          schema:
            $ref: ../../common/responses/error-403.yaml
        '422':
          description: ''
          schema:
            $ref: ../../common/responses/error-422.yaml
        '500':
          description: ''
          schema:
            $ref: ../../common/responses/error-500.yaml