swagger: '2.0'
info:
  title: v1
  version: '1.0'
host: stagingapi.webops.net/api
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
paths:
  /productSystems:
    post:
      operationId: product_systems
      summary: Get Product Systems
      
      parameters:
        - name: body
          in: body
          schema:
            allOf:
              - $ref: ../../common/message-data.yaml
              - $ref: ../../docs/productSystems/product-system-with-description-1.yaml
              - $ref: ../../common/updated.yaml
              - $ref: ../../common/paging.yaml
              - type: object
                properties:
                  includeProcedureDetails:
                    type: boolean
                    description: 'Include procedure categories in response - Default = false (Yes = true, No = false)'
                    example: true
                  includeKitFamilies:
                    type: boolean
                    description: 'Include kit families in response - Default = false (Yes = true, No = false)'
                    example: true
            description: Product Systems
        - $ref: ../../common/headers/authorization.yaml
        - $ref: ../../common/headers/access-token.yaml
      responses:
        '200':
          description: ''
          schema:
            type: object
            required:
              - messageId
              - timestamp
            properties:
              messageId:
                type: string
                example: 2d648c64-3eee-4fc7-9e19-df6f14c3fefd
                description: Message ID of the request
              timestamp:
                type: string
                format: date-time
                example: '2018-11-05T13:15:30Z'
                description: Current date/time in ISO-8601 Z format
              productSystems:
                type: array
                items:
                  $ref: ../../docs/productSystems/product-system-1.yaml
        '403':
          description: ''
          schema:
            $ref: ../../common/responses/error-403.yaml
        '422':
          description: ''
          schema:
            $ref: ../../common/responses/error-422.yaml
        '500':
          description: ''
          schema:
            $ref: ../../common/responses/error-500.yaml
  /productSystems/count:
    post:
      operationId: product_systems_count
      summary: Get total number of product systems per defined parameters. Must be used in conjunction with /product-systems.
      
      parameters:
        - name: body
          in: body
          schema:
            allOf:
              - $ref: ../../common/message-data.yaml
              - $ref: ../../docs/productSystems/product-system-identifiers-1.yaml
              - $ref: ../../common/updated.yaml
            description: Product Systems
        - $ref: ../../common/headers/authorization.yaml
        - $ref: ../../common/headers/access-token.yaml
      responses:
        '200':
          description: ''
          schema:
            $ref: ../../common/responses/count.yaml
        '403':
          description: ''
          schema:
            $ref: ../../common/responses/error-403.yaml
        '422':
          description: ''
          schema:
            $ref: ../../common/responses/error-422.yaml
        '500':
          description: ''
          schema:
            $ref: ../../common/responses/error-500.yaml