swagger: '2.0'
info:
  title: v1
  version: '1.0'
host: stagingapi.webops.net/api
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
paths:
  /salesReps:
    post:
      operationId: sales-reps
      summary: Get Sales Reps
      
      parameters:
        - name: body
          in: body
          schema:
            allOf:
              - $ref: ../../common/message-data.yaml
              - $ref: ../../docs/salesReps/sales-rep-identifiers-1.yaml
              - $ref: ../../common/updated.yaml
              - $ref: ../../common/paging.yaml
            description: Sales Reps
        - $ref: ../../common/headers/authorization.yaml
        - $ref: ../../common/headers/access-token.yaml
      responses:
        '200':
          description: ''
          schema:
            type: object
            required:
              - messageId
              - timestamp
            properties:
              messageId:
                type: string
                example: 2d648c64-3eee-4fc7-9e19-df6f14c3fefd
                description: Message ID of the request
              timestamp:
                type: string
                format: date-time
                example: '2018-11-05T13:15:30Z'
                description: Current date/time in ISO-8601 Z format
              salesReps:
                type: array
                items:
                  $ref: ../../docs/salesReps/sales-rep-1.yaml
        '403':
          description: ''
          schema:
            $ref: ../../common/responses/error-403.yaml
        '422':
          description: ''
          schema:
            $ref: ../../common/responses/error-422.yaml
        '500':
          description: ''
          schema:
            $ref: ../../common/responses/error-500.yaml
  /salesReps/count:
    post:
      operationId: sales_reps_count
      summary: Get total number of sales reps per defined parameters. Must be used in conjunction with /sales-reps.
      
      parameters:
        - name: body
          in: body
          schema:
            allOf:
              - $ref: ../../common/message-data.yaml
              - $ref: ../../docs/salesReps/sales-rep-identifiers-count-1.yaml
              - $ref: ../../common/updated.yaml
            description: Sales Reps
        - $ref: ../../common/headers/authorization.yaml
        - $ref: ../../common/headers/access-token.yaml
      responses:
        '200':
          description: ''
          schema:
            $ref: ../../common/responses/count.yaml
        '403':
          description: ''
          schema:
            $ref: ../../common/responses/error-403.yaml
        '422':
          description: ''
          schema:
            $ref: ../../common/responses/error-422.yaml
        '500':
          description: ''
          schema:
            $ref: ../../common/responses/error-500.yaml
  /salesReps/bulk:
    post:
      operationId: sales-reps-bulk-post
      summary: Post new sales reps in bulk
      
      parameters:
        - name: body
          in: body
          schema:
            allOf:
              - $ref: ../../common/message-data.yaml
              - $ref: ../../docs/salesReps/sales-rep-bulk-post-identifiers-1.yaml
            description: Sales Reps
        - $ref: ../../common/headers/authorization.yaml
        - $ref: ../../common/headers/access-token.yaml
      responses:
        '200':
          description: ''
          schema:
            type: object
            properties:
              messageId:
                type: string
                example: 2d648c64-3eee-4fc7-9e19-df6f14c3fefd
                description: Message ID of the request
              timestamp:
                type: string
                format: date-time
                example: '2018-11-05T13:15:30Z'
                description: Current date/time in ISO-8601 Z format
              code:
                type: integer
                description: One the defined response codes
                example: 1010
              message:
                type: string
                description: Text description
                example: Partial Success
              details:
                type: array
                description: Status of individual hospitals from the request.
                items:
                  $ref: ../../docs/salesReps/sales-rep-bulk-1.yaml
            required:
              - messageId
              - timestamp
              - code
              - message
              - details
        '403':
          description: ''
          schema:
            $ref: ../../common/responses/error-403.yaml
        '422':
          description: ''
          schema:
            $ref: ../../common/responses/error-422.yaml
        '500':
          description: ''
          schema:
            $ref: ../../common/responses/error-500.yaml
    put:
      operationId: sales-reps-bulk-put
      summary: Update sales reps in bulk
      
      parameters:
        - name: body
          in: body
          schema:
            allOf:
              - $ref: ../../common/message-data.yaml
              - $ref: ../../docs/salesReps/sales-rep-bulk-put-identifiers-1.yaml
            description: Sales Reps
        - $ref: ../../common/headers/authorization.yaml
        - $ref: ../../common/headers/access-token.yaml
      responses:
        '200':
          description: ''
          schema:
            type: object
            properties:
              messageId:
                type: string
                example: 2d648c64-3eee-4fc7-9e19-df6f14c3fefd
                description: Message ID of the request
              timestamp:
                type: string
                format: date-time
                example: '2018-11-05T13:15:30Z'
                description: Current date/time in ISO-8601 Z format
              code:
                type: integer
                description: One the defined response codes
                example: 1010
              message:
                type: string
                description: Text description
                example: Partial Success
              details:
                type: array
                description: Status of individual hospitals from the request.
                items:
                  $ref: ../../docs/salesReps/sales-rep-bulk-1.yaml
            required:
              - messageId
              - timestamp
              - code
              - message
              - details
        '403':
          description: ''
          schema:
            $ref: ../../common/responses/error-403.yaml
        '422':
          description: ''
          schema:
            $ref: ../../common/responses/error-422.yaml
        '500':
          description: ''
          schema:
            $ref: ../../common/responses/error-500.yaml